### ISSUE TITLE
Not consistent pom on Sonatype

### ISSUE THREAD

**Issue by wem** [gchauvet/vertx-async#1]
https://oss.sonatype.org/service/local/repositories/releases/content/io/zatarox/vertx-async/1.0.0/vertx-async-1.0.0.pom

version in the pom on the repo is 1.1.0-SNAPSHOT

**Comment by gchauvet** [comment]
Yes, I will fix that tonight. Thank you for this report !

**Comment by gchauvet** [comment]
I will push artifact tonight.

**Comment by gchauvet** [comment]
Artifact has been released on OSS. Will be available on central mvn repository in about 2 hours.

**Comment by wem** [comment]
Thx!
